package Start;

import Classes.UserManager;
import Classes.Users;
import Classes.Role;

import CUSTOMER.CustomerHomePageGUI;
import Doctor.DoctorMainMenu;
import Staff.ManageCustomer;

import javax.swing.JOptionPane;

public class LoginGUI extends javax.swing.JFrame {
    private UserManager userManager;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginGUI.class.getName());

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        userManager = new UserManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        tbViewPassword = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEmail.setText("Email:");

        lblPassword.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        tbViewPassword.setText("View");
        tbViewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbViewPasswordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("APU MEDICAL CENTRE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail)
                            .addComponent(pfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(tbViewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbViewPassword))
                .addGap(52, 52, 52)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String email = txtEmail.getText().trim();
        String password = new String(pfPassword.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both email and password.",
                    "Missing info", JOptionPane.WARNING_MESSAGE);
            if (email.isEmpty()) txtEmail.requestFocusInWindow();
            else pfPassword.requestFocusInWindow();
            return;
        }

        Users loggedInUser = userManager.login(email, password);

        if (loggedInUser == null) {
            JOptionPane.showMessageDialog(this, "Incorrect email or password.",
                    "Login Failed", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocusInWindow();
            return;
        }

        JOptionPane.showMessageDialog(this, "Login successful");
           
        Role r = loggedInUser.getRole();
        switch (r) {
            case DOCTOR -> {
                // Pass the concrete Doctor object for the OOP flow
                if (loggedInUser instanceof Classes.Doctor d) 
                {
                    new DoctorMainMenu(d, userManager).setVisible(true);
                    this.dispose();
                } else {
                    // Should not happen, but guard anyway
                    JOptionPane.showMessageDialog(this,
                            "Logged-in user is not a Doctor ",
                            "Type error", JOptionPane.ERROR_MESSAGE);
                }
            }
            case CUSTOMER -> {
                if (loggedInUser instanceof Classes.Customer c) {
                    new CUSTOMER.CustomerHomePageGUI(userManager, c).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(
                        this,
                        "Logged-in user is not a Customer",
                        "Type error",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
                break;
            }            
            case STAFF -> {
                if (loggedInUser instanceof Classes.Staff s) {
                    // pass the same userManager you logged in with
                    new Staff.ManageCustomer(userManager, s).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Logged-in user is not a Staff", "Type error", JOptionPane.ERROR_MESSAGE);
                }

        
        }
            case MANAGER -> {
                if (loggedInUser instanceof Classes.Manager) 
                {
                    new Manager.ManagerPage().setVisible(true);
                    this.dispose();
                } else {
                    // Error handling if anything happens in reading the role or text file
                    JOptionPane.showMessageDialog(this,
                            "Logged-in user is not a Doctor instance.",
                            "Type error", JOptionPane.ERROR_MESSAGE);
                }
            }
            default -> {
                JOptionPane.showMessageDialog(this,
                        "Unsupported role: " + loggedInUser.getRole(),
                        "Login", JOptionPane.WARNING_MESSAGE);
            }
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tbViewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbViewPasswordActionPerformed
        if(tbViewPassword.isSelected()){
            pfPassword.setEchoChar((char) 0);
        }
        else{
            pfPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_tbViewPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JToggleButton tbViewPassword;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
